parameters:
#    provider_alma.example.class: Provider\AlmaBundle\Example

services:
#    provider_alma.example:
#        class: %provider_alma.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
